version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: vrsoftware/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_DB=postgres
      - DB_PORT=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata: {}